name: TotemAnimations
version: 1.0
main: me.youhavetrouble.totemanimations.TotemAnimations
api-version: 1.14
folia-supported: true
commands:
  totemanimation:
    description: Displays totem animation
    permission: totemanimation.command
    usage: "Usage: totemanimation <player> <custom_model_data>"
permissions:
  totemanimation.command:
    default: op
    description: Allows usage of /totemanimation command
